name: Test

on: push

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Microchip Compilers
        run: >
          node scripts/install-compilers.js
          "http://ww1.microchip.com/downloads/en/DeviceDoc/xc8-v2.20-full-install-linux-installer.run"
          "http://ww1.microchip.com/downloads/en/DeviceDoc/xc16-v1.60-full-install-linux64-installer.run"
      - run: sudo du -hd 1 /opt/microchip
      - run: /opt/microchip/xc8/*/bin/xc8 --ver
      - run: /opt/microchip/xc16/*/bin/xc16-gcc --version
      - run: /opt/microchip/xc32/*/bin/xc32-gcc --version

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Microchip Compilers
        run: >
          node scripts/install-compilers.js
          "http://ww1.microchip.com/downloads/en/DeviceDoc/xc8-v2.20-full-install-windows-installer.exe"
          "http://ww1.microchip.com/downloads/en/DeviceDoc/xc16-v1.60-full-install-windows64-installer.exe"
          "http://ww1.microchip.com/downloads/en/DeviceDoc/xc32-v2.41-full-install-windows-installer.exe"
      - run: dir %PROGRAMFILES%/Microchip
      - run: dir %PROGRAMFILES(x86)%/Microchip

